import keyMirror from 'keymirror'

export default keyMirror({
  FORM_RESET_PASSWORD_API_NOT_AVAILABLE: null,
  FORM_RESET_PASSWORD_IN_PROCESS: null,
  FORM_RESET_PASSWORD_HASH_NOT_FOUND: null,
  FORM_RESET_PASSWORD_HASH_VALID: null,
  FORM_RESET_PASSWORD_SUBMIT_IN_PROCESS: null
})